// Auth types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SLATE_USER = "SET_SLATE_USER";
export const SET_SLATE_UPDATED_USER = "SET_SLATE_UPDATED_USER";
export const AUTH_DATA_LOADING_STATUS = "AUTH_DATA_LOADING_STATUS";
export const LOGOUT_USER = "LOGOUT_USER";



// task types
export const FETCH_CALENDAR_EVENTS = "FETCH_CALENDAR_EVENTS";
export const TASK_DATA_LOADING_STATUS = "TASK_DATA_LOADING_STATUS";
export const TASK_DATA_ADDING_STATUS = "TASK_DATA_ADDING_STATUS";


