// Auth types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";


// task types
export const FETCH_CALENDAR_EVENTS = "FETCH_CALENDAR_EVENTS";
export const TASK_DATA_LOADING_STATUS = "TASK_DATA_LOADING_STATUS";

